---
dist: xenial

sudo: required

language: java
jdk: openjdk8

cache:
  directories:
  - $HOME/.m2

before_install:
  - sudo apt-get install -y graphviz

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  local_dir: target/generated-html
  on:
    branch: master
